// Auto-generated from ExifTool GPS.pm (do not edit by hand)
use super::tags::{TagDef, SubDir};

pub static GPS_MAIN: &[TagDef] = &[
    TagDef { id: 0x0, name: "GPSVersionID", sub: SubDir::None },
    TagDef { id: 0x1, name: "GPSLatitudeRef", sub: SubDir::None },
    TagDef { id: 0x2, name: "GPSLatitude", sub: SubDir::None },
    TagDef { id: 0x3, name: "GPSLongitudeRef", sub: SubDir::None },
    TagDef { id: 0x4, name: "GPSLongitude", sub: SubDir::None },
    TagDef { id: 0x5, name: "GPSAltitudeRef", sub: SubDir::None },
    TagDef { id: 0x6, name: "GPSAltitude", sub: SubDir::None },
    TagDef { id: 0x7, name: "GPSTimeStamp", sub: SubDir::None },
    TagDef { id: 0x8, name: "GPSSatellites", sub: SubDir::None },
    TagDef { id: 0x9, name: "GPSStatus", sub: SubDir::None },
    TagDef { id: 0xa, name: "GPSMeasureMode", sub: SubDir::None },
    TagDef { id: 0xb, name: "GPSDOP", sub: SubDir::None },
    TagDef { id: 0xc, name: "GPSSpeedRef", sub: SubDir::None },
    TagDef { id: 0xd, name: "GPSSpeed", sub: SubDir::None },
    TagDef { id: 0xe, name: "GPSTrackRef", sub: SubDir::None },
    TagDef { id: 0xf, name: "GPSTrack", sub: SubDir::None },
    TagDef { id: 0x10, name: "GPSImgDirectionRef", sub: SubDir::None },
    TagDef { id: 0x11, name: "GPSImgDirection", sub: SubDir::None },
    TagDef { id: 0x12, name: "GPSMapDatum", sub: SubDir::None },
    TagDef { id: 0x13, name: "GPSDestLatitudeRef", sub: SubDir::None },
    TagDef { id: 0x14, name: "GPSDestLatitude", sub: SubDir::None },
    TagDef { id: 0x15, name: "GPSDestLongitudeRef", sub: SubDir::None },
    TagDef { id: 0x16, name: "GPSDestLongitude", sub: SubDir::None },
    TagDef { id: 0x17, name: "GPSDestBearingRef", sub: SubDir::None },
    TagDef { id: 0x18, name: "GPSDestBearing", sub: SubDir::None },
    TagDef { id: 0x19, name: "GPSDestDistanceRef", sub: SubDir::None },
    TagDef { id: 0x1a, name: "GPSDestDistance", sub: SubDir::None },
    TagDef { id: 0x1b, name: "GPSProcessingMethod", sub: SubDir::None },
    TagDef { id: 0x1c, name: "GPSAreaInformation", sub: SubDir::None },
    TagDef { id: 0x1d, name: "GPSDateStamp", sub: SubDir::None },
    TagDef { id: 0x1e, name: "GPSDifferential", sub: SubDir::None },
    TagDef { id: 0x1f, name: "GPSHPositioningError", sub: SubDir::None },
];
